DataBiosphere/terra-billing-profile-manager

.github/workflows/build-and-test.yml
.github/workflows/publish.yml
service/src/main/java/bio/terra/profile/app/controller/ProfileApiController.java

Getting CI setup for BPM and ready for a dev deployment
* Adds a publish action that fires on a new tag
* Adds a BPM specific slack hook instead of reusing the data catalog one

[WOR-315] Add publish action

---

README.md

No change, just testing the deploy workflow.

Testing deploy flow

---

service/src/main/java/bio/terra/profile/db/DaoKeyHolder.java
service/src/main/java/bio/terra/profile/db/ProfileDao.java
service/src/main/java/bio/terra/profile/service/profile/model/BillingProfile.java
service/src/main/resources/api/service_openapi.yaml
service/src/main/resources/db/changelog.xml
service/src/main/resources/db/changesets/20220713_billing_profiles_last_modified.yaml
service/src/test/java/bio/terra/profile/service/db/ProfileDaoTest.java
service/src/test/java/bio/terra/profile/service/profile/ProfileServiceUnitTest.java
service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileVerifyAccountStepTest.java
service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileVerifyDeployedApplicationStepTest.java

Adds last_modified to billing profile manager
https://broadworkbench.atlassian.net/browse/WOR-389

[WOR-389] Add last_modified to Billing Profile Manager (BPM)

---

service/src/main/java/bio/terra/profile/app/controller/ProfileApiController.java
service/src/main/java/bio/terra/profile/service/profile/ProfileService.java
service/src/main/resources/api/service_openapi.yaml
service/src/test/java/bio/terra/profile/service/profile/ProfileServiceUnitTest.java

Updates create profile to be synchronous 
https://broadworkbench.atlassian.net/browse/WOR-390

[WOR-390] Create Profile Sync

---

service/build.gradle
service/src/main/java/bio/terra/profile/app/StartupInitializer.java
service/src/main/java/bio/terra/profile/app/configuration/SentryConfiguration.java
service/src/main/java/bio/terra/profile/app/controller/GlobalExceptionHandler.java
service/src/main/resources/application.yml

Ticket: [WOR-370](https://broadworkbench.atlassian.net/browse/WOR-370)
* Integrate sentry into BPM
* Emit 5xx errors to sentry
Accompanying terra-helmfile PR to pull Sentry DSN from Vault so we can use it here https://github.com/broadinstitute/terra-helmfile/pull/3157
Tested by deploying these changes with accompanying terra-helmfile changes to dev BPM and inducing a 500. Exception was sent to sentry - https://sentry.io/organizations/broad-institute/issues/3479463794/?project=6608698

[WOR-370] Emit 5xx errors to sentry

---

README.md
render_configs.sh
service/src/main/resources/application.yml

[WOR-414](https://broadworkbench.atlassian.net/browse/WOR-414)
update config script to pull service azure creds from vault to local config file

WOR-414: Render BPM app azure client id, secret and tenant ID into local dev configs

---

.github/workflows/build-and-test.yml
buildSrc/src/main/groovy/bio.terra.profile.java-common-conventions.gradle
minnie-kenny.gitconfig
minnie-kenny.sh

Ticket: [WOR-487](https://broadworkbench.atlassian.net/browse/WOR-487)
* read more about minnie-kenny here: https://minnie-kenny.readthedocs.io/en/latest/

[WOR-487] setup minniekenny so building BPM will ensure that git-secrets is installed

---

.github/workflows/build-and-test.yml
README.md
buildSrc/src/main/groovy/bio.terra.profile.java-common-conventions.gradle
service/build.gradle

Ticket: [WOR-456](https://broadworkbench.atlassian.net/browse/WOR-456)
* still need to add the `SONAR_TOKEN` secret to the repo
* follows [Appsec documentation](https://app.gitbook.com/o/-LVj1clrBdFW94pG2z2w/s/-LsrggqZs3CYGFRhFZdX-887967055/appsec-team-internal/appsec-team-internal/security-activities/sast-1) and configuration found in ECM and DrsHub

[WOR-456] run sonarqube scan in build-and-test

---

service/src/main/java/bio/terra/profile/app/controller/ProfileApiController.java

Cleanup suggested in https://github.com/DataBiosphere/terra-billing-profile-manager/pull/39#discussion_r975434139

Remove unnecessary REST annotations (WOR-387).

---

service/src/main/java/bio/terra/profile/service/azure/AzureService.java
service/src/main/resources/api/service_openapi.yaml
service/src/test/java/bio/terra/profile/service/azure/AzureServiceUnitTest.java

https://broadworkbench.atlassian.net/browse/WOR-587

Include region name in managed app response (WOR-587).

---

service/src/main/resources/application.yml

Still trying to get to the point where I can manually test this, but the change is straightforward.

Add check for Microsoft.Relay (WOR-617).

---

buildSrc/build.gradle
service/build.gradle

I had put the dependencies in the buildSrc file instead of the service file.
Working locally:

Move the dependencies to the right file (WOR-547).

---

.github/dependabot.yml

My first attempt in https://github.com/DataBiosphere/terra-billing-profile-manager/pull/95 did not work (see https://github.com/DataBiosphere/terra-billing-profile-manager/pull/111). Trying a different syntax.

Try preventing major upgrades to spring-boot (WOR-680).

---

service/src/main/java/bio/terra/profile/app/common/ErrorReportUtils.java
service/src/main/java/bio/terra/profile/app/common/MdcHook.java
service/src/main/java/bio/terra/profile/app/configuration/StairwayDatabaseConfiguration.java
service/src/main/java/bio/terra/profile/app/controller/GlobalExceptionHandler.java
service/src/main/java/bio/terra/profile/app/controller/ProfileApiController.java
service/src/main/java/bio/terra/profile/service/iam/SamService.java
service/src/main/java/bio/terra/profile/service/job/JobBuilder.java
service/src/main/java/bio/terra/profile/service/job/JobService.java
service/src/main/java/bio/terra/profile/service/job/StairwayExceptionSerializer.java
service/src/main/java/bio/terra/profile/service/profile/ProfileService.java
service/src/test/java/bio/terra/profile/app/controller/AzureApiControllerTest.java
service/src/test/java/bio/terra/profile/service/profile/ProfileServiceUnitTest.java

This PR is cleaning up a handful of relatively quick code smells in BPM as [reported](https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=DataBiosphere_terra-billing-profile-manager) by sonarqube.

[WOR-896] Cleanup various sonar code smells

---

.github/workflows/build-and-test.yml
service/src/main/java/bio/terra/profile/service/azure/AzureService.java
service/src/test/java/bio/terra/profile/service/azure/AzureServiceUnitTest.java

Customer reported issue described in https://broadworkbench.atlassian.net/browse/WOR-994

Make authorized email check case-insensitive (WOR-994).

---

.github/workflows/verify_consumer_pacts.yml
service/build.gradle
service/src/test/java/bio/terra/profile/common/BaseSpringUnitTest.java
service/src/test/java/bio/terra/profile/pact/provider/BPMProviderTest.java
service/src/test/java/bio/terra/profile/pact/provider/ProviderStateData.java

[WOR-939](https://broadworkbench.atlassian.net/browse/WOR-939)
Set up provider side tests to run against consumer-generated pacts:
* add gradle task to verify pacts, with 
* sets up a reasonable spring test config with appropriate mocks
* pact broker integration with can-i-deploy
[WOR-939]: https://broadworkbench.atlassian.net/browse/WOR-939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WOR-939 BPM provider tests

---

service/src/main/java/bio/terra/profile/service/status/BaseStatusService.java
service/src/test/java/bio/terra/profile/pact/provider/BPMProviderTest.java

Ticket: https://broadworkbench.atlassian.net/browse/WOR-908
Provider-side pact test to be used by https://github.com/broadinstitute/rawls/pull/2400.
Note that more interesting verifications will follow… for my first I chose the least complicated endpoint.

Add provider contract for status check (WOR-908).

---

service/build.gradle
service/src/main/java/bio/terra/profile/app/controller/ProfileApiController.java
service/src/test/java/bio/terra/profile/pact/SamServiceTest.java
service/src/test/java/bio/terra/profile/pact/provider/BPMProviderTest.java

This implements the remainder of the provider support for https://github.com/broadinstitute/rawls/pull/2420.
Ticket: https://broadworkbench.atlassian.net/browse/WOR-908

Additional test cases (WOR-908).

---

.github/workflows/verify_consumer_pacts.yml
service/build.gradle

Changes recommended by @ichengchang

Fixes related to pact verification (WOR-908)

---

service/src/main/java/bio/terra/profile/app/StartupInitializer.java
service/src/main/java/bio/terra/profile/app/common/ErrorReportUtils.java
service/src/main/java/bio/terra/profile/app/common/MetricUtils.java
service/src/main/java/bio/terra/profile/service/iam/SamService.java
service/src/main/java/bio/terra/profile/service/spendreporting/azure/AzureCostManagementQuery.java
service/src/test/java/bio/terra/profile/common/MetricsUtilsUnitTest.java
service/src/test/java/bio/terra/profile/service/azure/AzureServiceUnitTest.java
service/src/test/java/bio/terra/profile/service/db/ProfileDaoTest.java
service/src/test/java/bio/terra/profile/service/iam/SamAuthenticatedUserRequestFactoryTest.java
service/src/test/java/bio/terra/profile/service/profile/ProfileServiceUnitTest.java
service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileFlightUnitTest.java
service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileVerifyAccountStepTest.java
service/src/test/java/bio/terra/profile/service/profile/flight/delete/DeleteProfileFlightTest.java
service/src/test/java/bio/terra/profile/service/status/ProfileStatusServiceTest.java

WOR-1160 - fix random sonar issues just to make some progress

[WOR-1160] Fix sonar issues in random order.

---

.github/workflows/consumer_contract_tests.yml
.github/workflows/tag.yml

Jira ticket: [QA-2166](https://broadworkbench.atlassian.net/browse/QA-2166)
Migrate BPM consumer pact to app version.
[QA-2166]: https://broadworkbench.atlassian.net/browse/QA-2166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

QA-2166: Migrate BPM consumer pact to app version

---

service/src/main/java/bio/terra/profile/service/policy/TpsApiDispatch.java

Ticket: [WOR-1366](https://broadworkbench.atlassian.net/browse/WOR-1366)
* Fix race condition where a PAO is created between when BPM fails to get it and when it tries to create one
See https://broadinstitute.slack.com/archives/C03GMG4DUSE/p1700595613892589 
[WOR-1366]: https://broadworkbench.atlassian.net/browse/WOR-1366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WOR-1366] Handle race condition in getOrCreatePao

---

README.md
service/build.gradle
service/src/main/java/bio/terra/profile/app/Main.java
service/src/main/java/bio/terra/profile/service/iam/SamService.java
service/src/main/java/bio/terra/profile/service/policy/TpsApiDispatch.java
service/src/main/resources/application.yml
service/src/test/java/bio/terra/profile/common/BaseSpringUnitTest.java
service/src/test/java/bio/terra/profile/pact/SamServiceTest.java

https://broadworkbench.atlassian.net/browse/WOR-1379
1. update TCL (which requires some config updates)
2. exclude /status and /version endpoints from tracing
3. cross service tracing to Sam and TPS

WOR-1379 tracing updates

---

service/build.gradle

https://broadworkbench.atlassian.net/browse/WOR-1389

WOR-1389 upgrade TCL to fix npe

---

.github/workflows/consumer_contract_tests.yml
.github/workflows/tag.yml
.github/workflows/verify_consumer_pacts.yml

Please refer to this [PR](https://github.com/DataBiosphere/github-actions/pull/44) on why we are changing bumper version to 0.3.0.

Change bumper version to 0.3.0

---

service/build.gradle

https://broadworkbench.atlassian.net/browse/WOR-1406

WOR-1406 update tcl for stairway tracing

---

.github/dependabot.yml
service/src/main/java/bio/terra/profile/app/controller/ProfileApiController.java

We don't want version updates for anything jersey in client-javax.

Fix syntax, ignore all of jersey for client-javax

---

service/build.gradle
service/src/main/java/bio/terra/profile/service/policy/TpsApiDispatch.java
service/src/main/java/bio/terra/profile/service/profile/ProfileService.java
service/src/test/java/bio/terra/profile/service/profile/ProfileServiceUnitTest.java

https://broadworkbench.atlassian.net/browse/WOR-1420

WOR-1420 use new TPS listPaos api

---

.github/workflows/build-and-test.yml

[NO TICKET] Fix name of channel.

---

service/src/main/java/bio/terra/profile/app/configuration/EnterpriseConfiguration.java
service/src/main/java/bio/terra/profile/service/profile/ProfileService.java
service/src/main/java/bio/terra/profile/service/profile/flight/ProfileMapKeys.java
service/src/main/java/bio/terra/profile/service/profile/flight/create/CreateProfileFinishStep.java
service/src/main/java/bio/terra/profile/service/profile/model/ProfileDescription.java
service/src/main/resources/api/service_openapi.yaml
service/src/main/resources/application.yml
service/src/test/java/bio/terra/profile/common/ProfileFixtures.java
service/src/test/java/bio/terra/profile/pact/provider/BPMProviderTest.java
service/src/test/java/bio/terra/profile/pact/provider/ProviderStateData.java
service/src/test/java/bio/terra/profile/service/profile/ProfileServiceUnitTest.java
service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileFlightTest.java

Ticket: [WOR-1580](https://broadworkbench.atlassian.net/browse/WOR-1580)
* When returning a billing profile, check its subscription against the allowlist of enterprise subscriptions to determine if it's an enterprise billing profile
[WOR-1580]: https://broadworkbench.atlassian.net/browse/WOR-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WOR-1580] Add organization to ProfileModel

---

service/src/main/java/bio/terra/profile/app/configuration/EnterpriseConfiguration.java
service/src/main/java/bio/terra/profile/service/profile/ProfileService.java
service/src/main/java/bio/terra/profile/service/profile/flight/ProfileMapKeys.java
service/src/main/java/bio/terra/profile/service/profile/flight/create/CreateProfileFinishStep.java
service/src/main/java/bio/terra/profile/service/profile/model/ProfileDescription.java
service/src/main/resources/api/service_openapi.yaml
service/src/main/resources/application.yml
service/src/test/java/bio/terra/profile/common/ProfileFixtures.java
service/src/test/java/bio/terra/profile/pact/provider/BPMProviderTest.java
service/src/test/java/bio/terra/profile/pact/provider/ProviderStateData.java
service/src/test/java/bio/terra/profile/service/profile/ProfileServiceUnitTest.java
service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileFlightTest.java

Ticket: [WOR-1580](https://broadworkbench.atlassian.net/browse/WOR-1580)
This reverts commit 7f50b2f093bc13443f6bf2ef854257e42d0c39a8.
Reverting due to upstream failures in Rawls when listing billing profiles
[WOR-1580]: https://broadworkbench.atlassian.net/browse/WOR-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WOR-1580] Revert "[WOR-1580] Add organization to ProfileModel (#436)"

---

service/src/main/java/bio/terra/profile/app/configuration/EnterpriseConfiguration.java
service/src/main/java/bio/terra/profile/service/profile/ProfileService.java
service/src/main/java/bio/terra/profile/service/profile/flight/ProfileMapKeys.java
service/src/main/java/bio/terra/profile/service/profile/flight/create/CreateProfileFinishStep.java
service/src/main/java/bio/terra/profile/service/profile/model/ProfileDescription.java
service/src/main/resources/api/service_openapi.yaml
service/src/main/resources/application.yml
service/src/test/java/bio/terra/profile/common/ProfileFixtures.java
service/src/test/java/bio/terra/profile/pact/provider/BPMProviderTest.java
service/src/test/java/bio/terra/profile/pact/provider/ProviderStateData.java
service/src/test/java/bio/terra/profile/service/profile/ProfileServiceUnitTest.java
service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileFlightTest.java

Ticket: [WOR-1580](https://broadworkbench.atlassian.net/browse/WOR-1580)
* Once https://github.com/broadinstitute/rawls/pull/2833 is merged, this can be reintroduced to BPM without breaking Rawls
This reverts commit 7e384b7ce35940e9be8b77edb25589c6d6dbfd7e.
[WOR-1580]: https://broadworkbench.atlassian.net/browse/WOR-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WOR-1580] Reintroduce organization to ProfileModel

---

service/src/main/java/bio/terra/profile/app/controller/GlobalExceptionHandler.java

404s in BPM are not handled gracefully; they can either spawn a 500 (due to not handling the generic NoResourceFoundException exception type in the global exception handler when non-api matching requests are made like bpm_host/api/foo) or a 403 which emits a ton of unneeded logging (like when a matching URL is hit but a specific profile resource is not found)

[WOR-1637] Handle not found exceptions

---

.github/workflows/consumer_contract_tests.yml

https://broadworkbench.atlassian.net/browse/WOR-1458
* Re-enable can-i-deploy for consumer contract tests (now that https://broadworkbench.atlassian.net/browse/WOR-890 is finished)
* publish all pacts in output directory to the broker

WOR-1458 - Pact Test Fixes

---

service/src/main/java/bio/terra/profile/service/iam/SamService.java
service/src/main/java/bio/terra/profile/service/iam/model/SamAction.java
service/src/main/java/bio/terra/profile/service/profile/ProfileService.java
service/src/test/java/bio/terra/profile/pact/provider/BPMProviderTest.java
service/src/test/java/bio/terra/profile/service/profile/ProfileServiceUnitTest.java
settings.gradle

https://broadworkbench.atlassian.net/browse/WOR-1769
see also https://github.com/broadinstitute/sam/pull/1489

WOR-1769 getProfile: check read_profile action instead allowing any action

---

.github/workflows/publish.yml

cuts over to using WIF for the publish sa we we don't have a hardcoded sa to maintain.

use WIF instead of hard-coded sa-key

---

service/src/main/java/bio/terra/profile/app/configuration/GcpConfiguration.java
service/src/main/java/bio/terra/profile/service/crl/GcpCrlService.java
service/src/main/java/bio/terra/profile/service/gcp/GcpService.java
service/src/main/java/bio/terra/profile/service/profile/ProfileService.java
service/src/main/java/bio/terra/profile/service/profile/flight/create/CreateProfileVerifyAccountStep.java
service/src/main/resources/application.yml
service/src/test/java/bio/terra/profile/service/gcp/GcpServiceUnitTest.java
service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileFlightTest.java

Ticket: https://broadworkbench.atlassian.net/browse/WOR-864
This ticket uses the BPM SA to check membership with the `terra-billing` group. See the Infosec Slack thread for details. https://broadinstitute.slack.com/archives/CADU7L0SZ/p1726149493982979
Tested with a locally running BPM.

[WOR-864] Check SA account access to verify Terra billing permissions

---

.github/workflows/build-and-test.yml

Ticket: [CORE-97](https://broadworkbench.atlassian.net/browse/CORE-97)
- move #dsp-workspaces-test-alerts to #dsp-core-services-alerts
[CORE-97]: https://broadworkbench.atlassian.net/browse/CORE-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CORE-97] Route Workspaces team alerts to Core Services slack channel

---

service/src/main/java/bio/terra/profile/app/configuration/AzureConfiguration.java
service/src/main/java/bio/terra/profile/app/configuration/PolicyServiceConfiguration.java
service/src/main/java/bio/terra/profile/app/controller/ProfileApiController.java
service/src/main/java/bio/terra/profile/service/crl/AzureCrlService.java
service/src/main/resources/application.yml
service/src/test/java/bio/terra/profile/service/azure/AzureServiceUnitTest.java
service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileVerifyDeployedApplicationStepTest.java

Part of large effort to add support for services to run in Azure Government cloud.
- Added environment variable for AZURE_ENVIRONMENT
https://broadworkbench.atlassian.net/browse/TOAZ-372
See related pull requests here:
[workbench-libs](https://github.com/broadinstitute/workbench-libs/pull/1713) [sam](https://github.com/broadinstitute/sam/pull/1603) [bpm](https://github.com/DataBiosphere/terra-billing-profile-manager/pull/505) [wsm](https://github.com/DataBiosphere/terra-workspace-manager/pull/1806) [cromwell](https://github.com/broadinstitute/cromwell/pull/7670) [terra-helmfile](https://github.com/broadinstitute/terra-helmfile/pull/5976)

Support for deployment in Azure Government Cloud  (BPM)
