DataBiosphere/terra-billing-profile-manager

.github/workflows/build-and-test.yml, .github/workflows/publish.yml, .github/workflows/tag.yml
ticket: [WOR-321](https://broadworkbench.atlassian.net/browse/WOR-321)
* updates how the publish action is triggered. Note that it can still be run manually, but will no longer run automatically when new tags are created
1. `build-and-test` action is run on merges to `main` branch and when new PRs are opened
2. If `build-and-test` action succeeds AND it was run on a merge to the `main` branch, then the `Tag, deploy, and publish` action (publish.yml) will be dispatched
3. This action first tags the current HEAD of the `main` branch using the tag.yml action
4. Then it goes through the rest of the already established steps to build and push the image as well as deploy the image to the Terra dev environment using the changes found in …
=> [WOR-321] trigger publish off successful test runs not new tags

.github/workflows/publish.yml, .github/workflows/tag.yml
Ticket: [WOR-321](https://broadworkbench.atlassian.net/browse/WOR-321)
**Fixes to publish and tag workflows**
* secrets weren't getting passed properly from publish.yml to tag.yml. adding `secrets: inherit` solved this problem
* there was an issue where the `bumper` action wasn't bumping the new version and there was no tag output which lead to failures in publish.yml. Bumping the `bumper` version to the most recent version fixed this.
* I changed `new_tag` to `tag` when trying to figure out why publish.yml couldn't find the tag properly. This probably wasn't necessary, but I like it more as we may not always have a _new_ tag, so `tag` seems slightly better and I'm leaving this change in
=> [WOR-321] Fixes to publish job

.github/workflows/publish.yml, buildSrc/src/main/groovy/bio.terra.profile.java-common-conventions.gradle, client/artifactory.gradle, service/build.gradle
We want to publish the BPM client for consumption by rawls and others
* Wires up the publish github action to publish the JAR to the [broad artifactory instance](http://broadinstitute.jfrog.io)
* Removes the terra-common-library as a global dependency that'll get included in any subproject (including the client subproject). This dependency was causing the pom generated during the publish step to include stairway and several other unwanted dependencies, which was causing issues downstream during testing in rawls. It is still being included as a dependency on the `service` project. 
* Published a snapshot version of the BPM client via the publish action to artifactory
* Pulled in the client JAR in a local Rawls. Verified that it can build and make calls to the dev BPM instance and get a 200 …
=> [WOR-319] Publish API client

service/src/main/java/bio/terra/profile/app/controller/AzureApiController.java, service/src/main/java/bio/terra/profile/db/ProfileDao.java, service/src/main/java/bio/terra/profile/service/azure/AzureService.java, service/src/main/java/bio/terra/profile/service/profile/flight/create/CreateProfileFlight.java, service/src/main/java/bio/terra/profile/service/profile/flight/create/CreateProfileVerifyDeployedApplicationStep.java, service/src/main/java/bio/terra/profile/service/profile/model/BillingProfile.java, service/src/main/resources/api/service_openapi.yaml, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20220803_billing_profiles_managed_resource_group_id.yaml, service/src/test/java/bio/terra/profile/common/BaseSpringUnitTest.java, service/src/test/java/bio/terra/profile/common/BaseUnitTest.java, service/src/test/java/bio/terra/profile/service/azure/AzureServiceUnitTest.java, service/src/test/java/bio/terra/profile/service/db/ProfileDaoTest.java, service/src/test/java/bio/terra/profile/service/iam/SamAuthenticatedUserRequestFactoryTest.java, service/src/test/java/bio/terra/profile/service/job/JobServiceTest.java, service/src/test/java/bio/terra/profile/service/profile/ProfileServiceUnitTest.java, service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileVerifyAccountStepTest.java, service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileVerifyDeployedApplicationStepTest.java, service/src/test/java/bio/terra/profile/service/status/BaseStatusServiceTest.java, service/src/test/java/bio/terra/profile/service/status/ProfileStatusServiceTest.java
There are a couple of problems with the current create profile code path with respect to Azure. 
It pulls the app down for access control checks by using the application deployment name and the parent resource group name. This is problematic because we:
1. Should be using the same code path for access control checks when enumerating managed apps via the /managedApps endpoint as we are when creating a profile
2. We need the managed resource group ID to be persisted with the profile so we can provide that to WSM downstream when creating workspace resources.
* Refactors the data model to swap out `applicationDeploymentName` + `resourceGroupName` for `managedResourceGroupId`
* Changes the profile creation logic to reuse the managed application enumeration codepath in `AzureService` as the …
=> [WOR-431] Adjust azure profile data model managed app coordinates

service/src/main/java/bio/terra/profile/app/configuration/AzureConfiguration.java, service/src/main/java/bio/terra/profile/service/azure/AzureService.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/profile/service/azure/AzureServiceUnitTest.java
[Relevant ticket](https://broadworkbench.atlassian.net/jira/software/c/projects/WOR/boards/125/backlog?view=detail&selectedIssue=WOR-454&issueLimit=100)
The way "well-known" Azure marketplace offers is configured in BPM is awkward and difficult to modify via helmfiles. 
(Quick refresher: well known offers are those Azure application offers whose deployments BPM will allow to be linked to billing profiles)
Specifically, having the offer name be a key and the auth'ed user key be a value makes setting the config via OS environment variables intractable in my research.
* Restructures how we configure well known application offers. The config is now an array of offer objects, with the keys being the offer name and the authed user key. The knock-on effect here is that we are able to set the …
=> Reworking well-known offers

service/src/main/java/bio/terra/profile/app/StartupInitializer.java, service/src/main/java/bio/terra/profile/app/configuration/SentryConfiguration.java, service/src/main/resources/application.yml
Ticket: [WOR-497](https://broadworkbench.atlassian.net/browse/WOR-497)
* Setting the environment in sentry's configuration will let us use the same Sentry project and still know which environment the issue is happening in
* Related terra-helmfile PR - https://github.com/broadinstitute/terra-helmfile/pull/3266
=> [WOR-497] set environment in sentry configuration

README.md, service/build.gradle, service/src/main/java/bio/terra/profile/app/controller/ProfileApiController.java, service/src/main/java/bio/terra/profile/service/iam/SamService.java, service/src/main/java/bio/terra/profile/service/profile/ProfileService.java, service/src/main/resources/api/service_openapi.yaml, service/src/main/resources/application.yml, service/src/test/java/bio/terra/profile/service/profile/ProfileServiceUnitTest.java, settings.gradle
Implements these endpoints for policies "user" and "owner", which map to roles "user" and "owner" respectively.
* GET /api/profiles/v1/{profileId}/policies
List the Sam resource policies for a billing profile.
* POST ​/api​/profiles/v1​/{profileId}​/policies​/{policyName}​/members​/{memberEmail}
Adds a member to the specified policy for the billing profile
* DELETE ​/api​/profiles/v1​/{profileId}​/policies​/{policyName}​/members​/{memberEmail}
Removes a member from the specified policy for the profile
The only information returned about a policy is its name and the member emails. For some discussion on this, see https://broadworkbench.atlassian.net/browse/WOR-391?focusedCommentId=66574
=> [WOR-391] Implement Sam passthroughs for profile policies

service/src/main/java/bio/terra/profile/app/controller/ProfileApiController.java, service/src/main/resources/api/service_openapi.yaml
Switch the API to specify the email address in the  body because the Java client errors with no body present. I tried specifying an empty body, but that actually led to a less intuitive API, and I still couldn't get it to work (problems serializing an empty bean).
FWIW, this change makes the API match the [jade-data-repo one](https://github.com/DataBiosphere/jade-data-repo/blob/aa3320d38cf88eadfb31fca4ced3777f14080e29/src/main/resources/api/data-repository-openapi.yaml#L354).
=> [WOR-387] Switch email from URL param to body.

service/src/main/java/bio/terra/profile/service/azure/ApplicationService.java, service/src/main/java/bio/terra/profile/service/azure/AzureService.java, service/src/main/java/bio/terra/profile/service/crl/CrlService.java, service/src/main/java/bio/terra/profile/service/profile/exception/DuplicateTagException.java, service/src/main/java/bio/terra/profile/service/profile/flight/create/CreateProfileFlight.java, service/src/main/java/bio/terra/profile/service/profile/flight/create/LinkBillingProfileIdToMrgStep.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/profile/service/azure/ApplicationServiceUnitTest.java
([Related ticket)](https://broadworkbench.atlassian.net/browse/WOR-520)
We need to tag an MRG with a billing profile ID at the time of creation so Sam can use it when creating a pet managed identity. This came up during testing in a BEE, while attempting to add a VM to an MRG for a workspace.
* Adds a new step to the azure create profile flight, which adds a tag to the MRG with the billing profile ID. 
* Adds related tests
=> [WOR-520] Tag Azure MRG with billing profile ID

service/src/main/java/bio/terra/profile/service/azure/ApplicationService.java, service/src/test/java/bio/terra/profile/service/azure/ApplicationServiceUnitTest.java
The previous PR was using the MRG ID, not the "fully qualified" mrg ID which is required when setting tags. 
That is, we need to use `/subscriptions/15fa50d6-105b-4eb2-8a07-a53ac7c142d9/resourceGroups/mrg-terra-dev-previ-20220921134324` vs. `mrg-terra-dev-previ-20220921134324` when setting tags via the `TagOperations` api.
=> [WOR-502] Use fully qualified ID when setting tags

service/src/main/java/bio/terra/profile/app/configuration/AzureConfiguration.java, service/src/main/java/bio/terra/profile/service/azure/AzureService.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/profile/service/azure/AzureServiceUnitTest.java
I was wearing my hacker hat this weekend (alright, I usually wear it) and realized that I don't think we are picky enough in the Azure app deployments we trust. Anybody could create an offer and name it `terra-dev`. This PR adds another restriction that an Azure app deployment must be from a configured publisher.
https://broadworkbench.atlassian.net/browse/WOR-546
=> WOR-546 ignore offers from wrong publishers

service/src/main/java/bio/terra/profile/app/controller/GlobalExceptionHandler.java, service/src/main/resources/api/service_openapi.yaml, service/src/test/java/bio/terra/profile/app/controller/AzureApiControllerTest.java, service/src/test/java/bio/terra/profile/common/BaseUnitTest.java
While looking into smoke tests for BPM, I found that we 500 when no subscription ID is passed to the `getManagedApps` endpoint. This PR fixes that issue by adding a global exception handler to return 400 on MethodArgumentTypeMismatchException and MissingServletRequestParameterException, as well as a test for the controller.
=> [WOR-551] Add azure controller test

service/src/main/java/bio/terra/profile/service/profile/flight/create/CreateProfileVerifyAccountStep.java, service/src/main/java/bio/terra/profile/service/profile/flight/create/CreateProfileVerifyDeployedApplicationStep.java, service/src/main/java/bio/terra/profile/service/profile/model/BillingProfile.java, service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileFlightTest.java, service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileVerifyAccountStepTest.java
This [sentry](https://sentry.io/organizations/broad-institute/issues/3653521049/?project=6608698&query=is%3Aunresolved) is caused by the [PR I merged here](https://github.com/DataBiosphere/terra-billing-profile-manager/pull/45/files). Specifically, the addition of the `getRequiredFoo` methods means Jackson will attempt to serialize those fields even for GCP profiles. 
We are lacking coverage for the `CreateProfileFlight`, so I've added that which gives us regression coverage on further serialization issues with this class and that flight in general.
=> [WOR-560] Add test for the create profile flight

service/generators.gradle, service/src/main/java/bio/terra/profile/app/configuration/VersionConfiguration.java
We are correctly building a version information file but are not looking in the correct place for it at runtime. Test output:
```
» curl -X 'GET' \                                                                       (gke_broad-dsde-qa_us-central1-a_terra-qa-bees/default)
'http://localhost:8080/version' \
-H 'accept: */*'
{"gitTag":"0.1.35","gitHash":"a4b29d9","github":"https://github.com/DataBiosphere/terra-billing-profile-manager/commit/a4b29d9","build":"0.1.35-SNAPSHOT"}%    ```
=> [WOR-496] Fix version endpoint

service/src/main/java/bio/terra/profile/service/profile/ProfileService.java, service/src/test/java/bio/terra/profile/service/profile/ProfileServiceUnitTest.java
We are returning 401 UNAUTHORIZED when a user does not have access to a profile. We should return 403 FORBIDDEN as that is a more accurate status code -- 401 generally indicates a bad authentication credential, which is not the case here. 403 should be used to indicate the credential is good but the server is not allowing access to the desired resource.
=> [WOR-515] Return 403 instead of 401 when user lacks access to a profile

service/src/main/java/bio/terra/profile/app/controller/AzureApiController.java, service/src/main/java/bio/terra/profile/db/ProfileDao.java, service/src/main/java/bio/terra/profile/service/azure/AzureService.java, service/src/main/java/bio/terra/profile/service/azure/model/ManagedAppCoordinates.java, service/src/main/java/bio/terra/profile/service/profile/exception/DuplicateManagedApplicationException.java, service/src/main/java/bio/terra/profile/service/profile/flight/create/CreateProfileVerifyDeployedApplicationStep.java, service/src/main/resources/api/service_openapi.yaml, service/src/main/resources/application.yml, service/src/main/resources/db/changelog.xml, service/src/main/resources/db/changesets/20221011_unique_managed_application.yaml, service/src/test/java/bio/terra/profile/service/azure/AzureServiceUnitTest.java, service/src/test/java/bio/terra/profile/service/db/ProfileDaoTest.java, service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileFlightTest.java, service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileVerifyDeployedApplicationStepTest.java
Ticket: [WOR-156](https://broadworkbench.atlassian.net/browse/WOR-156)
* add uniqueness constraint to prevent multiple billing profiles with the same managed app coordinates
* add optional query parameter to `listManagedApps` endpoint to specify whether to include managed apps that are already assigned to a billing profile
=> [WOR-156] Limit one billing profile per Azure managed app

.github/workflows/build-and-test.yml
We are encountering an issue with the lack of a `git say`, which causes `git secrets` to fail to install. This pulls in a workaround that I believe is working for Rawls.
=> Pull in this fix from rawls

buildSrc/src/main/groovy/bio.terra.profile.java-common-conventions.gradle
Ticket: [WOR-556](https://broadworkbench.atlassian.net/browse/WOR-556)
* Turns out we were explicitly setting the spring-framework version to avoid a different vulnerability. I removed this and confirmed that it now pulls in 5.3.23 instead of 5.3.18.
=> [WOR-556] Upgrade Spring to 5.3.23

.github/dependabot.yml
We have deferred upgrading spring-boot to 3.x (WOR-649), but should continue allowing 2.x upgrades. In particular, there is a 2.7.6 release, and I'm hoping this change allows dependabot to offer it.
Ignore syntax: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore
=> Allow spring-boot to continue with 2.x releases (WOR-652).

buildSrc/build.gradle, service/src/main/resources/application.yml
Following the lead of https://github.com/DataBiosphere/jade-data-repo/pull/768 and a [tutorial](https://www.tutorialworks.com/spring-boot-prometheus-micrometer/).
Note that this will just provide default metrics like JVM heap size. We can choose to add custom metrics later, but I would like to get the integration with prometheus working first.
After this is merged, I will experiment with how to scrape the data into prometheus. Muscles said this took some experimentation and devops help.
=> Enable micrometer and actuator (WOR-547).

service/src/main/java/bio/terra/profile/app/common/MetricUtils.java, service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileFlightTest.java, service/src/test/java/bio/terra/profile/service/profile/flight/delete/DeleteProfileFlightTest.java
Metrics need to start with their service name so they can potentially mix together on dashboards. [Slack conversation](https://broadinstitute.slack.com/archives/CADM7MZ35/p1670618699464539) with Jack.
=> Add metric namespace (WOR-547).

.github/workflows/publish.yml
Pretty much the same thing I did for WSM in https://github.com/DataBiosphere/terra-workspace-manager/pull/953
The behavior is a superset of the old behavior. The old behavior was "put v1.2.3 in dev". The new behavior is "tell devops about v1.2.3 including git info, put v1.2.3 in dev, then sync dev so it gets deployed immediately".
The "tell devops" step gives Sherlock a _ton_ more info to play with than the old mechanism this PR removes: we can show better accelerate metrics in Grafana and auto-generate changelogs in Beehive.
> **Note**
> There's an implementation change here beyond just "talk to Sherlock directly." The old mechanism fired off a dispatch to terra-helmfile and exited--pretty opaque from everyone's perspective except devops, at least at first glance.
>
> The new mechanism …
=> [DDO-2529] Deploy merged versions to Broad's dev env, the new way

service/src/main/java/bio/terra/profile/service/iam/SamService.java, service/src/main/java/bio/terra/profile/service/iam/model/SamRole.java
Ticket: [WOR-678](https://broadworkbench.atlassian.net/browse/WOR-678)
- Create empty pet-creator policy when creating new spend-profile resources in Sam. 
- Rawls will add new workspace writers to this policy
- We will not migrate existing spend-profile resources at this time
[WOR-678]: https://broadworkbench.atlassian.net/browse/WOR-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WOR-678] add pet-creator policy with pet-creator role to new spend-profiles

service/src/main/java/bio/terra/profile/service/azure/AzureService.java, service/src/test/java/bio/terra/profile/service/azure/AzureServiceUnitTest.java
[Related ticket](https://broadworkbench.atlassian.net/browse/WOR-729)
I bumped into this in my testing just now against the prod offer; BPM does not trim whitespace when presented with a CSV of authorized terra users in an offer.
=> [WOR-729] Trim whitespace when parsing the list of authed user emails

service/src/main/java/bio/terra/profile/app/Main.java, service/src/main/java/bio/terra/profile/app/configuration/NoCacheFilter.java
Ticket: [WOR-507](https://broadworkbench.atlassian.net/browse/WOR-507)
* set cache-control header to `no-store` so that browsers will not cache the returned content. This header is set only on `/api/*` endpoints as it is not needed for unauthenticated requests
Before:
```
curl -X GET 'http://localhost:8080/api/profiles/v1?offset=0&limit=10' --header "Authorization: Bearer `gcloud auth print-access-token marc.testbott@gmail.com`" -i
HTTP/1.1 200 
X-Request-ID: axzk5MzR
Content-Type: application/json
Content-Length: 481
```
After:
```
curl -X GET 'http://localhost:8080/api/profiles/v1?offset=0&limit=10' --header "Authorization: Bearer `gcloud auth print-access-token marc.testbott@gmail.com`" -i                                                            
HTTP/1.1 200 
Cache-Control: no-store …
```
=> [WOR-507] Set no-store Cache-Control header on all authenticated APIs

service/src/main/java/bio/terra/profile/service/azure/ApplicationService.java, service/src/main/java/bio/terra/profile/service/azure/exception/InaccessibleSubscriptionException.java, service/src/test/java/bio/terra/profile/service/azure/ApplicationServiceUnitTest.java
[Relevant ticket](https://broadworkbench.atlassian.net/browse/WOR-767)
BPM will 500 attempting to inspect a subscription for managed app deployments. This PR catches the related management exceptions and instead returns 404. The cause will still be logged for further diagnostics if necessary.
=> [WOR-767] Handle management exceptions for inaccessible Azure subscriptions

service/build.gradle
Ticket: [WOR-714](https://broadworkbench.atlassian.net/browse/WOR-714)
- Tested by attempting to create a GCP billing profile with two different users, one with access to the Google billing account and one without. `CreateProfileVerifyAccountStep` (what uses the GCP billing CRL library) failed as expected for the user without access and succeeded for the one that did. 
[WOR-714]: https://broadworkbench.atlassian.net/browse/WOR-714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WOR-714] Bump cloud-resource-library version

.github/actions/bump-skip/action.yml, .github/workflows/build-and-test.yml, .github/workflows/consumer_contract_tests.yml
We erroneously fire off a tag+publish+deploy on version bumps, which means we are attempting to tag+publish+deploy the same version twice which [results](https://github.com/DataBiosphere/terra-billing-profile-manager/actions/workflows/publish.yml) in a 409 in sherlock. This PR adds a check for version bump merges.
=> [WOR-892] Do not dispatch tag if this is a version bump

.github/dependabot.yml
[WOR-891](https://broadworkbench.atlassian.net/browse/WOR-891)
We don't want dependabot to upgrade any of the pact libs
[WOR-891]: https://broadworkbench.atlassian.net/browse/WOR-891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> widen dependabot exclusion scope to cover all pact libraries

service/src/main/resources/application.yml
We should retain stairway flight records for at least 90 days for diagnostic purposes.
=> [WOR-981] Increase flight retention interval

service/src/test/java/bio/terra/profile/pact/SamServiceTest.java
[WOR-890](https://broadworkbench.atlassian.net/browse/WOR-890)
remove auth header from pact setup
Authentication is out of scope for what we're testing in pact. 
The header was originally added to the things checked in the pact setup in the early stages of implementation.
[WOR-890]: https://broadworkbench.atlassian.net/browse/WOR-890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WOR-890 follow up on Sam consumer tests

buildSrc/build.gradle, service/build.gradle
Ticket: [WOR-1001](https://broadworkbench.atlassian.net/browse/WOR-1001)
* new versions of TCL and terra-test-runner use 0.9.3 of jose4j
[WOR-1001]: https://broadworkbench.atlassian.net/browse/WOR-1001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WOR-1001] Bump tcl and terra-test-runner

.github/workflows/build-and-test.yml, buildSrc/src/main/groovy/bio.terra.profile.java-common-conventions.gradle
* We should get a test and build report so we can get more details about test failures.
* Test failures should go to # dsp-workspace-test-alerts
=> [WOR-1036] Output build report

service/src/test/java/bio/terra/profile/pact/SamServiceTest.java
Jira ticket associated with this PR: [QA-2075](https://broadworkbench.atlassian.net/browse/QA-2075)
The Sam provider will support token vs no token states for user status info request.
Please also refer to this [PR](https://github.com/DataBiosphere/terra-workspace-data-service/pull/293).
[QA-2075]: https://broadworkbench.atlassian.net/browse/QA-2075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> QA-2075: Add state and http header to user status info request.

service/src/main/resources/application.yml
[Ticket](https://broadworkbench.atlassian.net/browse/WOR-1194)
Large access tokens exceed the default configured spring boot header size limit of 8k. I have not been able to reproduce this behavior using any available google accounts, but artificially lowering the spring max header size does reproduce the reported behavior.
This PR bumps the max header size to 32kb in an attempt to mitigate the issue.
=> [WOR-1194] Set max header size to 32KB

service/src/main/resources/application.yml
https://broadworkbench.atlassian.net/browse/WOR-1220
This came from a UL thread: https://broadinstitute.slack.com/archives/CBJJ7U293/p1692981855371259
The user was getting this error creating a BP:
```
Landing Zone creation failed: Failed to construct exception: com.azure.core.management.exception.ManagementException; Exception message: Status code 409, "{"error":{"code":"MissingSubscriptionRegistration","message":"The subscription is not registered to use namespace 'Microsoft.ManagedIdentity'. See https://aka.ms/rps-not-found for how to register subscriptions.","details":[{"code":"MissingSubscriptionRegistration","target":"Microsoft.ManagedIdentity","message":"The subscription is not registered to use namespace 'Microsoft.ManagedIdentity'. See https://aka.ms/rps-not-found for how to …
```
=> [WOR-1220] Microsoft.ManagedIdentity resource provider is required

buildSrc/build.gradle, buildSrc/src/main/groovy/bio.terra.profile.java-common-conventions.gradle, service/build.gradle, service/src/main/java/bio/terra/profile/service/iam/SamService.java, service/src/main/java/bio/terra/profile/service/job/JobBuilder.java, service/src/main/java/bio/terra/profile/service/job/JobService.java
Verily security has started using a different dependency analysis tool which flagged a handful of vulnerabilities. I'd like to update dependencies to fix issues raised by both Verily's tool and Sourceclear.
I verified the dependency versions are changed by generating lockfiles locally, though it looks like this service generally isn't using them anymore so I didn't include them in this PR.
=> [PF-2972] Update dependencies to address security vulnerabilities

.github/workflows/consumer_contract_tests.yml, .github/workflows/verify_consumer_pacts.yml, service/src/test/java/bio/terra/profile/pact/SamServiceTest.java, service/src/test/java/bio/terra/profile/pact/provider/BPMProviderTest.java
Prefer helmchart name as the pacticipant identifier:
* `bpm-provider` -> `bpm`
* `bpm-consumer` -> `bpm`
* `sam-provider` -> `sam`
* See [thread](https://broadinstitute.slack.com/archives/C043YJ40719/p1698068076950019) discussing the `-consumer` and `-provider` suffix anti-pattern.
* See [thread](https://broadinstitute.slack.com/archives/C043YJ40719/p1698241095600099) discussing the recommendation to use the helm chart name.
Unblocks:
* https://github.com/broadinstitute/rawls/pull/2610
* https://github.com/DataBiosphere/terra-workspace-manager/pull/1511
* https://github.com/broadinstitute/sam/pull/1234
Tickets:
[AJ-1428](https://broadworkbench.atlassian.net/browse/AJ-1428) - General maintenance ticket.
[AJ-1234](https://broadworkbench.atlassian.net/browse/AJ-1234) - Adjacent / similar, …
=> Use helmchart name for pact identifier.

foundation.yaml
This is a functional no-op PR that just adds a metadata file to the bpm repo that is used to ingest bpm into [DSP's backstage instance](https://backstage.dsp-devops.broadinstitute.org/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned). Backstage is an internal platform tool that can be used for a lot of SDLC processes and improving Dev experience. DevOps is just starting to experiment with this as a means to make getting a new service stood up in the terra environments and through the prod readiness checklist easier.
But we also want all our existing services to be in the system so they can get any benefits.
=> DDO-3198 Add Metadata Yaml File to  to ingest bpm into DSP backstage

foundation.yaml
Sorry for the PR spam. I had a typo in the path reference to BPM's open api spec. DevOps has some tooling that consumes these `foundation.yaml` metadata files off the `main` branch of our github repos but it makes it a bit tricky to fully vet them before they are merged.
=> DDO-3198 Fix Typo in path reference to OpenApi Spec

.github/workflows/consumer_contract_tests.yml, .github/workflows/tag.yml, .github/workflows/verify_consumer_pacts.yml
Ticket: [QA-2177](https://broadworkbench.atlassian.net/browse/QA-2177)
To prevent bumper action to dispatch `semver` tag more than once on PR merge.
[QA-2177]: https://broadworkbench.atlassian.net/browse/QA-2177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> QA-2177: Regulate the jobs that use bumper action, to prevent tag dispatch during workflows other than "Tag, publish, deploy".

.github/workflows/verify_consumer_pacts.yml, service/src/test/java/bio/terra/profile/pact/provider/BPMProviderTest.java
The BPM provider is missing consumer version selector, this is causing the provider to verify only the HEAD version of the consumer pact. Adding the selector enables the provider to verify the correct `CONSUMER_BRANCH` specified in the Pact Broker webhook payload. This will fix the issue @marctalbott reported about the missing verification result record in PB.
=> QA-2178: Add consumer version selector to provider test

service/src/test/java/bio/terra/profile/pact/provider/ProviderStateData.java
Ticket: [WOR-1037](https://broadworkbench.atlassian.net/browse/WOR-1037)
* The Rawls pact tests are still failing to verify against BPM. Hopefully this will fix it by adding an empty array for the `policies` field to the profile response rather than not including the `policies` field at all.
[WOR-1037]: https://broadworkbench.atlassian.net/browse/WOR-1037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WOR-1037] Use empty TpsPolicyInputs in pact provider state data

service/src/test/java/bio/terra/profile/pact/provider/BPMProviderTest.java
Ticket: [WOR-1037](https://broadworkbench.atlassian.net/browse/WOR-1037)
* BPM wasn't including policies in its provider test responses because the PAO included in the mocked TPS response didn't have any attributes set. Add an empty set of attributes to the mocked PAO. I was actually able to test this one locally and saw that BPM was able to verify the Rawls consumer pact
[WOR-1037]: https://broadworkbench.atlassian.net/browse/WOR-1037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WOR-1037] Add empty effectiveAttributes to mocked TPS response for BPM provider tests

.github/dependabot.yml
This pull request sets some ignore rules for dependabot to avoid updates for specific libraries. Some library updates might force us to use "jakarta" namespace instead of current "javax". This particular "client-javax" module is not supposed to use "jakarta" since this module is used by Rawls which doesn't support jakarta yet. Currently there are 2 modules which represents API client libs: 1) "client" (support jakarta) 2) client-javax (doesn't support jakarta)
=> WOR-1369 [BPM] Configure dependabot to ignore some updates for client-javax module

.github/workflows/build-and-test.yml, buildSrc/build.gradle, buildSrc/src/main/groovy/bio.terra.profile.java-common-conventions.gradle
[Ticket](https://broadworkbench.atlassian.net/browse/WOR-1398)
We get the needed coverage from sonarcloud and spotbugs 6.x SARIF files are incompatible with the codeql upload action.
=> Remove spotbugs

service/src/main/java/bio/terra/profile/app/controller/GlobalExceptionHandler.java, service/src/main/java/bio/terra/profile/service/profile/exception/InvalidFieldException.java, service/src/main/java/bio/terra/profile/service/profile/model/BillingProfile.java, service/src/test/java/bio/terra/profile/app/controller/SpendReportingApiControllerTest.java
Playing around with BPM creating GCP billing profiles, I bumped into a few issues:
* Submitting a billing account ID larger than the varchar field in the DB allows leaks the details of the `INSERT` statement in the API error 😢 . I've added a global exception handler that will catch the data source exceptions and give back a more opaque internal server error
* Related, I've added validation that the billing account ID field fits in 32 chars and if not gives back an `InvalidFieldException` 
* Using a bad access token will no longer give back the slightly wonky `Error getting user email from Sam:`; instead it will return a plain "Unauthorized" message.
* Breaks out a separate handler for the mismatched arg type handling to give back more meaningful error messages (i.e., when the date for …
=> [WOR-1413] Clean up our error handling during billing profile creation

.github/dependabot.yml
To cut down on the number of individual PRs, group minor release updates (which should have no breaking changes) together.
=> [NO TICKET] Group dependabot upgrades.

service/src/main/resources/application.yml
https://broadworkbench.atlassian.net/browse/WOR-1439
BPM was already publishing Micrometer metrics to Prometheus for exposure in Grafana.  This PR adds additional configuration to collect percentile histogram metrics, which will enable us to visualize per-endpoint percentile latencies across different dimensions (e.g. broken up by status).
**Manual Verification**
These metrics only show up for an endpoint when a request is made.  I ran a local BPM, navigated to Swagger, and hit the `/status` endpoint several times.
I then navigated to `http://localhost:9098/actuator/prometheus` and verified that metrics were being collected for my interactions:
```
_server_requests_seconds_bucket{error="none",exception="none",method="GET",outcome="SUCCESS",status="200",uri="/status",le="0.003495251",} 1.0 …
```
=> [WOR-1439] Micrometer: publish percentile histograms for per-endpoint latencies

.github/dependabot.yml
Adds the long-lived ticket to dependabot PRs and excludes spotless from PR grouping, as it often requires code changes.
Also added the grouping configuration to `client-javax`. I didn't scroll down far enough to see it the last time. :/
=> [NO TICKET] Updates to dependabot configuration.

service/src/main/java/bio/terra/profile/service/spendreporting/azure/AzureSpendReportingService.java, service/src/main/java/bio/terra/profile/service/spendreporting/azure/exception/UnexpectedCostManagementDataFormat.java, service/src/main/java/bio/terra/profile/service/spendreporting/azure/model/AzureResourceProviderType.java, service/src/main/java/bio/terra/profile/service/spendreporting/azure/model/SpendCategoryType.java, service/src/main/java/bio/terra/profile/service/spendreporting/azure/model/mapper/QueryResultMapper.java, service/src/main/java/bio/terra/profile/service/spendreporting/azure/model/mapper/SpendDataItemCategoryMapper.java, service/src/main/java/bio/terra/profile/service/spendreporting/azure/model/mapper/SpendDataMapper.java, service/src/main/resources/api/service_openapi.yaml, service/src/test/java/bio/terra/profile/common/SpendDataFixtures.java, service/src/test/java/bio/terra/profile/service/spendreporting/azure/AzureSpendReportingServiceUnitTest.java, service/src/test/java/bio/terra/profile/service/spendreporting/azure/model/mapper/QueryResultMapperUnitTest.java, service/src/test/java/bio/terra/profile/service/spendreporting/azure/model/mapper/SpendDataItemCategoryMapperUnitTest.java
This change introduce:
1. new spend report category - "WorkspaceInfrastructure'. This category includes all resources under K8s node resource group. Everything else will go to "Compute/Storate/Other" categories:
2. adjustment to Compute category. This will include all resources with the following resource providers type "microsoft.compute", "microsoft.batch" which reside in MRG
3. adjustment to Storage category. This will include all resources with the following resource providers type "microsoft.storage" which reside in MRG
4. Everything else will go to Other category.
=> WOR-1373 Billing Project user feedback: Update cost groupings in ToA Billing Project spend report.

buildSrc/build.gradle, service/build.gradle, service/src/test/java/bio/terra/profile/pact/SamServiceTest.java
https://broadworkbench.atlassian.net/browse/WOR-1520
We previously constrained `org.json:json` to move past a vulnerable version when pulled in as a transitive dependency.  The only place where this happened was within the Sam client.
Now that the Sam client no longer presents this vulnerability, we can remove the constraint along with updating Sam client.
This simplifies dependency management: one less dependency for Dependabot to chase.  On merging this PR, https://github.com/DataBiosphere/terra-billing-profile-manager/pull/403 should close automatically (I'll circle back to it to make sure).
Verified:
```
(base) okotsopo@wm111-e35 terra-billing-profile-manager % ./gradlew :service:dependencyInsight --dependency org.json:json
…
> Task :service:dependencyInsight
org.json:json:20240205 …
```
=> [WOR-1520] Upgrade Sam client, remove json constraint

buildSrc/src/main/groovy/bio.terra.profile.java-spring-conventions.gradle
https://broadworkbench.atlassian.net/browse/WOR-1533
Our current version of Spring Boot is [3.1.2](https://github.com/DataBiosphere/terra-billing-profile-manager/blob/d2501ad8d2d6065c78236245bf74fa7fdebd244d/buildSrc/build.gradle#L18), which [brings in postgresql 42.6.0](https://github.com/spring-projects/spring-boot/blob/v3.1.2/spring-boot-project/spring-boot-dependencies/build.gradle#L1096-L1102).
To mitigate a security vulnerability, we must instruct Spring Boot use a non-vulnerable version.
I first tried upgrading our TCL to see if that would fix things but this had no impact: the Spring Boot pin was both necessary and sufficient, so I will pursue the TCL upgrade separately as it's a larger change.
=> [WOR-1533] Spring Boot dependency: pin postgresql to 42.7.2

service/src/main/java/bio/terra/profile/app/configuration/PolicyServiceConfiguration.java, service/src/main/resources/application.yml
Support getting auth token from azure workload identity instead of gcp service account to auth with TPS. Equivalent to this PR in WSM https://github.com/DataBiosphere/terra-workspace-manager/pull/1548
=> [WOR-1563] Support running on AKS

service/build.gradle, service/src/main/java/bio/terra/profile/service/crl/GcpCrlService.java
Ticket: [WOR-1562](https://broadworkbench.atlassian.net/browse/WOR-1562)
* We need to use a Google access token to for Google API calls. The token in the `AuthenticatedUserRequest` can be either a B2C JWT or a Google access token. If the token is a B2C JWT, it will have the user's Google access token included as a `idp_access_token` claim which we need to use for Google API calls. If the token isn't a JWT, we assume it's a valid Google access token and attempt to use it anyways.
[WOR-1562]: https://broadworkbench.atlassian.net/browse/WOR-1562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WOR-1562] Use Google access token for Google calls

service/src/main/java/bio/terra/profile/app/configuration/AzureConfiguration.java, service/src/main/java/bio/terra/profile/app/configuration/PolicyServiceConfiguration.java, service/src/main/java/bio/terra/profile/app/controller/AzureApiController.java, service/src/main/java/bio/terra/profile/service/azure/AzureService.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/profile/service/azure/AzureServiceUnitTest.java, service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileVerifyDeployedApplicationStepTest.java
- Uses the azure-control-plane-enabled feature flag to switch between finding Marketplace/ServiceCatalog deployed apps
- For ServiceCatlog deployed apps, we don't use the publisher or plan AMA properties, instead we are looking at the kind (''ServiceCatalog") and matching up the authuser email
- New test for ServiceCatalog app kind
=> [TOAZ-343]: api/azure/v1/managedApps support for ServiceCatalog deployed azure managed apps

README.md, buildSrc/build.gradle, buildSrc/src/main/groovy/bio.terra.profile.java-common-conventions.gradle, buildSrc/src/main/groovy/bio.terra.profile.java-spring-conventions.gradle, service/build.gradle, service/src/main/java/bio/terra/profile/app/common/MDCHandlingException.java, service/src/main/java/bio/terra/profile/app/common/MdcHook.java, service/src/main/java/bio/terra/profile/service/job/JobBuilder.java, service/src/main/java/bio/terra/profile/service/job/JobService.java, service/src/test/java/bio/terra/profile/service/profile/ProfileServiceUnitTest.java
This reverts commit 530a866b93b2fd528b07ea8eb85e01f2bf46c8b3.
Reason: TCL's upgrade to k8s client 20.0.1 broke its KubePodListener, which could affect the recovery of Stairway flights.
=> Revert "[WOR-1560] Upgrade to TCL 1.1.1 for MDC-aware Stairway (#418)"

buildSrc/build.gradle
We previously applied this upgrade which included a Liquibase upgrade 4.21.0 -> 4.24.0. But when we reverted the commit due to an issue with TCL's k8s client 20.0.1 upgrade and KubePodListener, the downgrade resulted in Liquibase failing to match the checksums:
```
Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
4 changesets check sum
db/changesets/20220117_billing_profiles.yaml::billing_profile_table::rtitle was: 9:6420a46fc88868b10ef94c8275cb0489 but is now: 8:f732f2df183e22616dcb346addf171f5
db/changesets/20220713_billing_profiles_last_modified.yaml::billing_profile_table_last_modified::ypark was: 9:72418b78fbc7b6d7ebb7b6b4a2e6e9d8 but is now: 8:ab33ec314b191a61defe7c5332cae9a6
db/changesets/20220803_billing_profiles_managed_resource_group_id.yaml::billing_p …
```
=> [WOR-1560] Upgrade Spring Boot 3.1.2 -> 3.2.3

service/build.gradle
This versions transitive dependency on k8s client at 20.0.1 (was 20.0.1-legacy) including KubePodListener fixes to work with the non-legacy client.
Related TCL PR: https://github.com/DataBiosphere/terra-common-lib/pull/174
=> [WOR-1448] Upgrade TCL 1.1.4 -> 1.1.6

service/build.gradle
Pulling in the latest TCL to bump bouncy-castle to fix a CVE.
[Source clear run on main illustrating the presence of the CVE for bouncy-castle](https://github.com/broadinstitute/dsp-appsec-sourceclear-github-actions/actions/runs/9080538162/job/24952229115)
[Clean source clear run against this branch](https://github.com/broadinstitute/dsp-appsec-sourceclear-github-actions/actions/runs/9080620910/job/24952527896
)
=> [WOR-1652] Bump TCL to pull in bouncy-castle fix

service/src/main/java/bio/terra/profile/app/configuration/LimitsConfiguration.java, service/src/main/java/bio/terra/profile/service/profile/ProfileService.java, service/src/main/resources/api/service_openapi.yaml, service/src/main/resources/application.yml, service/src/test/java/bio/terra/profile/service/profile/ProfileServiceUnitTest.java
https://broadworkbench.atlassian.net/browse/AJ-1835
Adds the "limits" map to a billing profile's organization.  This will be used to identify which billing profiles have limits imposed, e.g. for Anvil Lite.  Verified in my BEE that Rawls can still communicate with BPM without needing to update its model (although we will want to do that).
Example of what the config would look like here: https://github.com/broadinstitute/terra-helmfile/pull/5564
=> [AJ-1835] Add limits to BPM profile/organization

service/src/test/java/bio/terra/profile/pact/provider/BPMProviderTest.java
https://broadworkbench.atlassian.net/browse/WOR-1769
need to add a new state to the pact tests so that I have something to update when permission checking changes in https://github.com/DataBiosphere/terra-billing-profile-manager/pull/464
[see this test run](https://github.com/DataBiosphere/terra-billing-profile-manager/actions/runs/9940778571/job/27458338812#step:8:476) for proof that this new state works with [the test in the WSM PR](https://github.com/DataBiosphere/terra-workspace-manager/pull/1774).
=> WOR-1769 add state for missing billing profile pact test

service/src/main/java/bio/terra/profile/app/controller/ProfileApiController.java, service/src/main/java/bio/terra/profile/service/iam/SamService.java, service/src/main/java/bio/terra/profile/service/profile/ProfileService.java, service/src/main/resources/api/service_openapi.yaml, service/src/test/java/bio/terra/profile/pact/provider/BPMProviderTest.java, service/src/test/java/bio/terra/profile/service/profile/ProfileServiceUnitTest.java
Ticket: [https://broadworkbench.atlassian.net/browse/WOR-1706](https://broadworkbench.atlassian.net/browse/WOR-1706)
Adds support for Sam `leaveResource` to be used in BPM. Then use that to create a new BPM endpoint, `leaveProfile`, which removes the authenticated user from a billing profile.
Updated unit tests and contract testing between Rawls and BPM.
=> [WOR-1706] Add leaveProfile endpoint

.github/workflows/verify_consumer_pacts.yml
updates this workflow to use a new version in dsp-resuable-workflow, gets rid of the workflow-dispatch + vault calls, so should 
1) give better visibility / simplifly flow
2) deprecates vault usage
=> update to use dsp-reusable-workflows, also no vault

service/src/main/java/bio/terra/profile/db/ProfileDao.java, service/src/main/java/bio/terra/profile/service/profile/flight/create/CreateProfileFlight.java, service/src/main/java/bio/terra/profile/service/profile/flight/create/CreateProfileStep.java, service/src/test/java/bio/terra/profile/db/ProfileDaoTest.java, service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileFlightTest.java
https://broadworkbench.atlassian.net/browse/WOR-1805
This PR changes the BillingProfile.createdBy field to store the user's ID (user.getSubjectId()) instead of their email. It also updates the logic to use initiatingUser when specified, ensuring consistent behavior with the changelog.
- BillingProfile.createdBy: Now stores the user's ID instead of their email.
- initiatingUser: Now used when specified, matching the changelog behavior.
- Updated tests to ensure correct storage of user IDs and proper handling of initiatingUser.
=> WOR-1805 Update BillingProfile.createdBy to Use User ID

service/src/main/java/bio/terra/profile/app/configuration/GcpConfiguration.java, service/src/main/java/bio/terra/profile/service/crl/GcpCrlService.java, service/src/main/java/bio/terra/profile/service/gcp/GcpService.java, service/src/main/java/bio/terra/profile/service/profile/ProfileService.java, service/src/main/java/bio/terra/profile/service/profile/flight/create/CreateProfileVerifyAccountStep.java, service/src/main/resources/application.yml, service/src/test/java/bio/terra/profile/service/gcp/GcpServiceUnitTest.java, service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileFlightTest.java
Reverts DataBiosphere/terra-billing-profile-manager#482
Reintroduces the changes for WOR-864, which did not work when merged to develop because a necessary the new variable in [application.yml](https://github.com/DataBiosphere/terra-billing-profile-manager/pull/483/files#diff-4dab07009b19ea187f607a407b00997345505227a852e7115e4dcd086f27a388R93) was not present in deployed environments. The needed change to the BPM deployment template is in https://github.com/broadinstitute/terra-helmfile/pull/5868.
=> Revert "Revert "[WOR-864] Check SA account access to verify Terra billing permissions""

.github/dependabot.yml
Dependabot automatically tags an associated ticket and the workspaces team. The ticket was moved from WS to CORE; this PR updates the ticket and which team is tagged on dependabot updates.
=> [CORE-69] Move automatic dependency updates to CORE from Workspaces

.github/workflows/publish.yml, .github/workflows/verify_consumer_pacts.yml
The cache backend service has been rewritten from the ground up for improved performance and reliability. [actions/cache](https://github.com/actions/cache) now integrates with the new cache service (v2) APIs.
The new service will gradually roll out as of February 1st, 2025. The legacy service will also be sunset on the same date. Changes in these release are fully backward compatible.
More info here: https://github.com/marketplace/actions/cache
=> CORE-246 Upgrading to cache v4

service/build.gradle
partially supersedes #526  .
That other PR attempts to bump the git properties plugin, but causes gradle errors. This PR has the same bump, but also includes the appropriate gradle fix from `https://github.com/n0mer/gradle-git-properties/pull/235`.
=> CORE-69: bump git properties plugin to 2.5.0, with compatibility fixes

buildSrc/build.gradle, buildSrc/src/main/groovy/bio.terra.profile.java-common-conventions.gradle, buildSrc/src/main/groovy/bio.terra.profile.java-spring-conventions.gradle, service/build.gradle, service/src/main/resources/application.yml
TCL 1.1.28 is the minimum upgrade that has the k8s client we need. This TCL upgrade carries a Spring Boot upgrade from 3.2.3 to 3.4.1; upgrading further would carry even more upgrades. I suggest we tackle further upgrades in (a) follow-on PR(s).
In this PR:
* upgrade TCL 1.1.11 -> 1.1.28
* upgrade Spring Boot 3.2.3 -> 3.41
* add an exclude to `terra-policy-client` to avoid otel-related Spring autoconfig conflicts
NOT in this PR, suggest we handle in future PR(s):
- resolve Spring warnings on `@MockBean`/`@SpyBean`
- upgrade TCL and Spring Boot to latest versions
=> CORE-391: upgrade TCL to 1.1.28

service/src/test/java/bio/terra/profile/app/controller/AzureApiControllerTest.java, service/src/test/java/bio/terra/profile/app/controller/SpendReportingApiControllerTest.java, service/src/test/java/bio/terra/profile/pact/provider/BPMProviderTest.java, service/src/test/java/bio/terra/profile/service/job/JobServiceTest.java, service/src/test/java/bio/terra/profile/service/profile/flight/create/CreateProfileFlightTest.java, service/src/test/java/bio/terra/profile/service/profile/flight/delete/DeleteProfileFlightTest.java, service/src/test/java/bio/terra/profile/service/status/ProfileStatusServiceTest.java
#531, as part of upgrading terra-common-lib, upgraded Spring Boot.
The newer version of Spring Boot deprecates `@MockBean` in favor of `@MockitoBean` and logs warnings during compilation when `@MockBean` is used.
This PR switches all usages of `@MockBean` to `@MockitoBean`.
=> CORE-391: MockBean -> MockitoBean

service/src/main/java/bio/terra/profile/app/configuration/WebConfig.java
#531, as part of upgrading terra-common-lib, upgraded Spring Boot.
The Spring Boot upgrade carried a behavior change to `WebMvcConfigurer`. This behavior change caused BPM's swagger-ui to fail because it couldn't find `/webjars/swagger-ui-dist/swagger-ui-bundle.js`.
This PR fixes that!
=> CORE-391: fix swagger-ui re:spring boot upgrade

buildSrc/build.gradle, buildSrc/src/main/groovy/bio.terra.profile.java-common-conventions.gradle, service/build.gradle
#531 upgraded terra-common-lib to 1.1.28, which was the minimum required version to continue working on our live k8s clusters.
This PR upgrades to 1.1.38, which is the latest version. It carries upgrades to a few other dependencies for compatibility.
=> CORE-391: update to latest TCL

service/build.gradle, service/src/main/resources/application.yml
Update TCL to get its fix for the "failed to export spans" error.
See https://github.com/DataBiosphere/terra-common-lib/pull/229
Tested by running locally, seeing no errors logged, and seeing traces reported to GCP.
=> CORE-376: turn off double-tracing and 'failed to export spans' error
